# Generated by Django 5.0.6 on 2024-05-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_alter_camera_cname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
